### ISSUE TITLE
Simulation start in Softrealtime and Hardrealtime Mode

### ISSUE THREAD

**Issue by dev-gb** [modelica/dcp-standard#1]
Had some troubles while sending the STC_run pdu to slaves.
Since the starting time of master and slaves are not synchronized by the standard the simulation starts at an undefined time. 

would be great if the time could be set by the master or read via a PDU. 
At the moment, the example DcpSlave implementation prohibits the test execution if the master clock is in front of the other. **So the simulation can never be started at a specific point in time.**

Would be better if the start_time was defined as seconds until the start of the simulation.

**Comment by debuti** [comment]
"Proper clock synchronization techniques have to be performed before starting the simulation (PTP, NTP, ..)" although applicable to most of the situations where OSs or middlewares are present, this issue is an impediment for barebone systems with no clock management facilities. Moreover, some clock drifts may appear under long simulations and they need to be taken into account.

**Comment by martinkrammer** [comment]
* Master and slave pairs need to be synchronized (have a common perception of time, or master needs to know at least the offset to each slave)
* DCP does not correct any clock drift/skew
* DCP defines "start now" when timestamp is set to zero "0", see p44-45 in the spec
Thus,
Relative time to start would not bring any benefits
Master must be aware of slave's offsets (to be determined with e.g. 1588), but slaves do not care about master's time
There is no need for clock adjustment (e.g. OS, middleware) in DCP

**Comment by martinkrammer** [comment]
No change in specification needed, as polled in meeting.
